---
- name: Configuring computer
  hosts: localhost
  become: true
  tasks:
    - name: Pre config
      include_tasks: src/steps/pre-config/tasks.yml
      include_vars: src/steps/pre-config/vars.yml
