---
- name: Configuring computer
  hosts: localhost
  become: true
  vars:
    my_username: dantas
    my_main_group: dantas
  tasks:
    - name: Pre config
      include_tasks:
        file: src/steps/pre-config/main.yml
