---
- name: Configuring computer
  hosts: localhost
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Project management config
      include_tasks:
        file: src/steps/project-management/main.yml

    - name: Python dev tools config
      include_tasks:
        file: src/steps/python-dev-tools/main.yml

    - name: Cloud tools installation
      include_tasks:
        file: src/steps/cloud-tools/main.yml

    - name: Docker config
      include_tasks:
        file: src/steps/docker/main.yml

    - name: Installing softwares
      include_tasks:
        file: src/steps/softwares/main.yml

  handlers:
    - include: src/handlers.yml
