---
- name: Configuring computer
  hosts: localhost
  become: true
  vars:
    my_username: dantas
    my_main_group: dantas

  tasks:
    - name: Project management config
      include_tasks:
        file: src/steps/project-management/main.yml

    - name: Basic dev tools config
      include_tasks:
        file: src/steps/dev-tools/main.yml

  handlers:
    - include: src/handlers.yml
