---
pre_requirements:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

cron_vars:
  name: ansible_docker-cleanup
  script_path: /opt/scripts/docker-cleanup.sh
  description: Clean up of docker
